/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineelectionsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author Nadam_2kg0od8
 */
public class UserPage extends javax.swing.JFrame {

    private static final String db = "jdbc:mysql://localhost:3306/onlineelection?";  
    private static final String username = "root";  
    private static final String password = "1234";
    String ElecName;
    Connection con = null; 
    PreparedStatement stat = null ;
    ResultSet ret = null;
    Election e ;
    MyQuery Q ;
    User uup ;
    Candidate c; 

    
    
    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
        try {
            con = DriverManager.getConnection(db , username, password);
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        setElectionName();
    }

    
    public void setElectionName(){
      try{
         String sql = "select * from Election";
         stat = con.prepareStatement(sql);
         ret = stat.executeQuery();
         while(ret.next())
         {
             ElectionsName.addItem(ret.getString("Name"));
         }  
         System.out.println("added successfully");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ElectionsName = new javax.swing.JComboBox<>();
        candidateName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Hello Voter,");

        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("your vote matters!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Which candidate you vote?");

        ElectionsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElectionsNameActionPerformed(evt);
            }
        });

        candidateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Which election you search?");

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("vote");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ElectionsName, 0, 208, Short.MAX_VALUE)
                            .addComponent(candidateName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel4)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(92, 92, 92)
                .addComponent(ElectionsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(candidateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElectionsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectionsNameActionPerformed
        // TODO add your handling code here:
        candidateName.removeAllItems();
     /*    try{
         String sql = "select ElecID from Election where Name="+ElectionsName.getSelectedItem();
         stat = con.prepareStatement(sql);
         ret = stat.executeQuery();
         if(ret.next())
         {
           e = new Election(ret.getInt("ElecID"), ret.getString("Name"),ret.getString("Description") ,ret.getString("StartDate"), ret.getString("EndDate"));
         }  
         System.out.println("added successfully");
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    */
        
        Q = new MyQuery();
        ArrayList<Candidate> list = Q.getData((String)ElectionsName.getSelectedItem());
        for(int i = 0 ;i < list.size() ;i++)
        {
            candidateName.addItem(list.get(i).getName());
        }
            
        
    }//GEN-LAST:event_ElectionsNameActionPerformed

    private void candidateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateNameActionPerformed
        // TODO add your handling code here:
      try{
     
        
      }catch(Exception e)
      {
          
      }
        
        
    }//GEN-LAST:event_candidateNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try{
        String sql = "select * from candidate where Name=?";
        stat = con.prepareStatement(sql);
        stat.setString(1, candidateName.getSelectedItem().toString());
        ret = stat.executeQuery();
        if(ret.next())
        {
            c = new Candidate(ret.getInt("CandID"), ret.getInt("elecID"), ret.getString("Name"), ret.getString("Description"));
        }
              
        sql = "insert into User(SSN,elecID,candID) value(?,?,?)";
        stat = con.prepareStatement(sql);
        stat.setString(1, uup.getSSN());
        stat.setString(2, Integer.toString(Q.ID));
        stat.setString(3, Integer.toString(c.getCandID()));
        stat.executeUpdate();
              System.out.println("inserted successfully");
              
              
        sql = "select NumofVote from candidate where CandID=?";
        stat = con.prepareStatement(sql);
        stat.setString(1, Integer.toString(c.getCandID()));
        ret = stat.executeQuery();
        int value =0;
        if(ret.next())
        {
            value =Integer.valueOf(ret.getString("NumofVote"));
        }
        value++ ;
        
        sql = "update candidate set NumofVote=? where CandID=?";
        stat = con.prepareStatement(sql);
        stat.setString(1, Integer.toString(value));
        stat.setString(2, Integer.toString(c.getCandID()));
        stat.execute();
              System.out.println(value);
        //con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        LoginPage1 lp = new LoginPage1();
        lp.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
/* public ArrayList<Candidate> getData(String id)
    {
        ArrayList<Candidate> l = new ArrayList<Candidate>();
         try{
         String sql = "select * from candidate where elecID="+id;
         stat = con.prepareStatement(sql);
         ret = stat.executeQuery();
        
         Candidate c ;
         while(ret.next())
         {
             c = new Candidate(ret.getInt("CandID"), ret.getInt("elecID"),ret.getString("Name") , ret.getString("Description"));
             l.add(c);
         }
             System.out.println(l.size());
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
         
       return l;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ElectionsName;
    private javax.swing.JComboBox<String> candidateName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
